# Hexo Configuration

# Site
title: Baiyang
subtitle: '数字 IC / SoC / RISC-V / AI 加速器'
description: 'Welcome to Visit My Blogs!'
keywords:
  - 数字IC
  - SoC
  - RISC-V
  - AI加速器
  - CPU设计
author: Baiyang
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://Faris-chip.github.io/Weblog
root: /Weblog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - '@traptitech/markdown-it-katex'
  images:
    prepend_root: true
    post_asset: true

# Home page setting
index_generator:
  path: ''
  per_page: 15
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 25
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: fluid

# Deployment
deploy:
  type: ''
